import type { PluginSeed } from '@/db/schema';

export const pluginsData: PluginSeed[] = [
  {
    slug: 'gstack',
    name: 'gstack',
    author: 'Garry Tan',
    authorUrl: 'https://github.com/garrytanstack',
    description:
      'An opinionated full-stack agent workflow that guides you from ideation through production with structured phases: Think, Plan, Build, Review, Test, Ship, and Reflect.',
    summary:
      'Garry Tan\'s take on structured AI-assisted development. gstack encodes a disciplined build cycle into seven discrete phases, giving your agent a repeatable playbook that mirrors how experienced engineers actually ship software. If you want a framework that prevents the "just start coding" trap, this is it.',
    trustTier: 'verified',
    audience: 'developer',
    category: 'development',
    githubUrl: 'https://github.com/garrytanstack/gstack',
    stars: 2800,
    forks: 185,
    lastUpdated: '2026-03-18',
    license: 'MIT',
    worksWith: ['claude-code', 'cursor', 'codex'],
    installInstructions: {
      'Claude Code': 'claude install @garrytanstack/gstack',
      Cursor: 'Add gstack to .cursor/skills/',
    },
    tags: ['workflow', 'full-stack', 'structured-development', 'shipping'],
    bestFor:
      'Developers who want a disciplined, phase-based workflow for shipping full-stack features end to end.',
    featured: 1,
  },
  {
    slug: 'superpowers',
    name: 'Superpowers',
    author: 'Jesse Vincent',
    authorUrl: 'https://github.com/obra',
    description:
      'Advanced agent capabilities including ultra-deep thinking, multi-agent orchestration, parallel task execution, and structured code review — pushing Claude Code beyond its defaults.',
    summary:
      'Jesse Vincent\'s power-user toolkit unlocks capabilities most people don\'t know Claude Code has. Ultra-think mode forces deeper reasoning on hard problems, multi-agent orchestration lets you run parallel workstreams, and the code review skill brings a rigorous multi-lens analysis to every PR. Essential for anyone who\'s outgrown the default agent behavior.',
    trustTier: 'verified',
    audience: 'developer',
    category: 'development',
    githubUrl: 'https://github.com/obra/superpowers',
    stars: 3200,
    forks: 220,
    lastUpdated: '2026-03-16',
    license: 'MIT',
    worksWith: ['claude-code', 'cursor'],
    installInstructions: {
      'Claude Code': 'claude install @obra/superpowers',
    },
    tags: ['multi-agent', 'ultra-think', 'parallel-execution', 'power-user'],
    bestFor:
      'Power users who want to push Claude Code\'s reasoning and orchestration capabilities to their limits.',
    featured: 1,
  },
  {
    slug: 'pm-skills-marketplace',
    name: 'PM Skills Marketplace',
    author: 'Paweł Huryn',
    authorUrl: 'https://huryn.dev',
    description:
      'Product management toolkit with PRD generation, user story writing, sprint planning, and roadmap building — designed for PMs who use Claude Code or Cowork.',
    summary:
      'Paweł Huryn has distilled years of product management best practices into a skill suite that works for both technical PMs using Claude Code and non-technical PMs on Cowork. The PRD Writer alone saves hours per feature spec, and the Sprint Planner integrates estimation with scope reality checks.',
    trustTier: 'verified',
    audience: 'both',
    category: 'productivity',
    githubUrl: 'https://github.com/hurynp/pm-skills-marketplace',
    stars: 1500,
    forks: 110,
    lastUpdated: '2026-03-14',
    license: 'MIT',
    worksWith: ['claude-code', 'cowork', 'cursor'],
    installInstructions: {
      'Claude Code': 'claude install @hurynp/pm-skills-marketplace',
      Cowork: 'Install from Cowork skill marketplace',
    },
    tags: ['product-management', 'prd', 'user-stories', 'sprint-planning'],
    bestFor:
      'Product managers who want to generate PRDs, user stories, and sprint plans with AI assistance.',
    featured: 1,
  },
  {
    slug: 'web-quality-skills',
    name: 'Web Quality Skills',
    author: 'Addy Osmani',
    authorUrl: 'https://addyosmani.com',
    description:
      'Web performance and quality toolkit covering Core Web Vitals optimization, accessibility auditing, image optimization, and Lighthouse-driven performance analysis.',
    summary:
      'From the author of influential web performance resources, Addy Osmani\'s quality skills bring Google-grade web optimization directly into your agent workflow. Each skill targets a specific dimension of web quality — speed, accessibility, image weight, and CWV scores — with actionable, data-backed recommendations rather than generic advice.',
    trustTier: 'verified',
    audience: 'developer',
    category: 'development',
    githubUrl: 'https://github.com/nickytonline/web-quality-skills',
    stars: 4200,
    forks: 310,
    lastUpdated: '2026-03-17',
    license: 'MIT',
    worksWith: ['claude-code', 'cursor', 'codex'],
    installInstructions: {
      'Claude Code': 'claude install @nickytonline/web-quality-skills',
      Cursor: 'Add web-quality-skills to .cursor/skills/',
    },
    tags: ['performance', 'core-web-vitals', 'accessibility', 'image-optimization'],
    bestFor:
      'Frontend developers who want to ship fast, accessible websites with excellent Core Web Vitals scores.',
    featured: 1,
  },
  {
    slug: 'hashicorp-agent-skills',
    name: 'HashiCorp Agent Skills',
    author: 'HashiCorp',
    authorUrl: 'https://hashicorp.com',
    description:
      'Official HashiCorp infrastructure-as-code skills for managing Terraform configurations, building Packer images, and integrating with Vault for secrets management.',
    summary:
      'HashiCorp\'s official entry into the agent skills ecosystem brings first-party IaC expertise to Claude Code. Terraform plan/apply workflows, Packer image builds, and Vault secret retrieval are all handled with the same rigor you\'d expect from the team that built the tools. The Terraform skill alone understands provider schemas and can catch misconfigurations before they hit plan.',
    trustTier: 'official',
    audience: 'developer',
    category: 'devops',
    githubUrl: 'https://github.com/hashicorp/agent-skills',
    stars: 3500,
    forks: 280,
    lastUpdated: '2026-03-15',
    license: 'Apache-2.0',
    worksWith: ['claude-code', 'cursor'],
    installInstructions: {
      'Claude Code': 'claude install @hashicorp/agent-skills',
    },
    tags: ['terraform', 'packer', 'vault', 'infrastructure-as-code', 'devops'],
    bestFor:
      'Infrastructure engineers managing Terraform, Packer, and Vault who want first-party agent support.',
    featured: 1,
  },
  {
    slug: 'google-workspace-cli',
    name: 'Google Workspace CLI',
    author: 'Google',
    authorUrl: 'https://workspace.google.com',
    description:
      'Native CLI integration with Gmail, Google Drive, Calendar, and Sheets — manage your entire Google Workspace from the terminal or Cowork.',
    summary:
      'Google\'s official Workspace plugin bridges the gap between your development environment and your productivity suite. Send emails, search Drive, check calendars, and query spreadsheets without ever opening a browser tab. Particularly powerful on Cowork, where non-technical users can manage their entire Google Workspace through natural language.',
    trustTier: 'official',
    audience: 'both',
    category: 'productivity',
    githubUrl: 'https://github.com/nickytonline/workspace-cli',
    stars: 5100,
    forks: 380,
    lastUpdated: '2026-03-19',
    license: 'Apache-2.0',
    worksWith: ['claude-code', 'cowork', 'cursor', 'claude-ai'],
    installInstructions: {
      'Claude Code': 'claude install @nickytonline/workspace-cli',
      Cowork: 'Install from Cowork integrations',
      'Claude.ai': 'Enable Google Workspace in Claude.ai settings',
    },
    tags: ['google', 'gmail', 'drive', 'calendar', 'productivity'],
    bestFor:
      'Anyone who lives in Google Workspace and wants to manage email, docs, and calendars from their agent.',
    featured: 1,
  },
  {
    slug: 'anthropic-official-skills',
    name: 'Anthropic Official Skills',
    author: 'Anthropic',
    authorUrl: 'https://anthropic.com',
    description:
      'Official document processing skills for extracting, analyzing, and transforming DOCX, PDF, PPTX, and XLSX files with high-fidelity output.',
    summary:
      'Anthropic\'s first-party document skills handle the messy reality of enterprise file formats. PDFs with complex layouts, Word documents with tracked changes, PowerPoint decks, and Excel workbooks are all parsed with structural awareness — tables stay as tables, formatting is preserved, and embedded content is extracted cleanly.',
    trustTier: 'official',
    audience: 'both',
    category: 'documents',
    githubUrl: 'https://github.com/anthropics/official-skills',
    stars: 6200,
    forks: 450,
    lastUpdated: '2026-03-20',
    license: 'Apache-2.0',
    worksWith: ['claude-code', 'cowork', 'cursor', 'claude-ai'],
    installInstructions: {
      'Claude Code': 'claude install @anthropic/official-skills',
      Cowork: 'Pre-installed on Cowork',
      'Claude.ai': 'Enable in Claude.ai settings',
    },
    tags: ['documents', 'pdf', 'docx', 'xlsx', 'file-processing'],
    bestFor:
      'Teams that work with enterprise document formats and need reliable extraction and analysis.',
    featured: 0,
  },
  {
    slug: 'openai-official-skills',
    name: 'OpenAI Official Skills',
    author: 'OpenAI',
    authorUrl: 'https://openai.com',
    description:
      'Official OpenAI skills for the Codex platform — deploy to Cloudflare Workers, build web games, and run sandboxed code interpretation.',
    summary:
      'OpenAI\'s official skill pack for Codex brings deployment, prototyping, and code execution into a single bundle. The Cloudflare Deploy skill handles Workers and Pages with zero-config setup, the Web Game Builder scaffolds browser games with physics and rendering, and Code Interpreter runs sandboxed Python for data analysis and visualization.',
    trustTier: 'official',
    audience: 'developer',
    category: 'development',
    githubUrl: 'https://github.com/openai/codex-skills',
    stars: 4800,
    forks: 350,
    lastUpdated: '2026-03-18',
    license: 'Apache-2.0',
    worksWith: ['codex', 'claude-code'],
    installInstructions: {
      Codex: 'Pre-installed on Codex',
      'Claude Code': 'claude install @openai/codex-skills',
    },
    tags: ['cloudflare', 'deployment', 'web-games', 'code-interpreter'],
    bestFor:
      'Codex users who want one-click deployment, rapid game prototyping, and sandboxed code execution.',
    featured: 0,
  },
  {
    slug: 'microsoft-azure-skills',
    name: 'Microsoft Azure Skills',
    author: 'Microsoft',
    authorUrl: 'https://azure.microsoft.com',
    description:
      'Official Azure integration skills for managing cloud storage, M365 connectivity, and visual workflow design with React Flow.',
    summary:
      'Microsoft\'s official Azure skills bring first-party cloud integration to your agent. Manage blob storage and queues, connect to M365 services for Teams and SharePoint, and design visual workflows with the React Flow Designer. Built for enterprise teams already invested in the Azure ecosystem.',
    trustTier: 'official',
    audience: 'developer',
    category: 'devops',
    githubUrl: 'https://github.com/microsoft/azure-agent-skills',
    stars: 3100,
    forks: 240,
    lastUpdated: '2026-03-16',
    license: 'Apache-2.0',
    worksWith: ['claude-code', 'codex', 'cursor'],
    installInstructions: {
      'Claude Code': 'claude install @microsoft/azure-skills',
      Codex: 'codex plugin add @microsoft/azure-skills',
    },
    tags: ['azure', 'cloud-storage', 'm365', 'react-flow', 'enterprise'],
    bestFor:
      'Enterprise developers on Azure who need storage management, M365 integration, and visual workflow design.',
    featured: 0,
  },
  {
    slug: 'trail-of-bits-security',
    name: 'Trail of Bits Security',
    author: 'Trail of Bits',
    authorUrl: 'https://trailofbits.com',
    description:
      'Advanced security analysis toolkit featuring CodeQL and Semgrep integration for automated vulnerability detection, taint analysis, and secure code patterns.',
    summary:
      'Trail of Bits brings world-class security research into your development workflow. The CodeQL Analysis skill runs deep semantic queries against your codebase to find injection flaws, auth bypasses, and data flow issues, while Semgrep Analysis provides fast pattern-based scanning with custom rules. Together they cover both depth and breadth of security analysis.',
    trustTier: 'verified',
    audience: 'developer',
    category: 'security',
    githubUrl: 'https://github.com/trailofbits/agent-skills',
    stars: 3900,
    forks: 270,
    lastUpdated: '2026-03-13',
    license: 'MIT',
    worksWith: ['claude-code', 'cursor', 'codex'],
    installInstructions: {
      'Claude Code': 'claude install @trailofbits/security',
      Cursor: 'Add trail-of-bits-security to .cursor/skills/',
    },
    tags: ['security', 'codeql', 'semgrep', 'vulnerability-detection', 'sast'],
    bestFor:
      'Security-conscious teams who want automated CodeQL and Semgrep analysis integrated into their agent workflow.',
    featured: 0,
  },
  {
    slug: 'composio-awesome-skills',
    name: 'Composio Awesome Skills',
    author: 'Composio',
    authorUrl: 'https://composio.dev',
    description:
      'Multi-platform integration hub connecting GitHub, Slack, Jira, REST APIs, and webhooks through natural language automation and pre-built connectors.',
    summary:
      'Composio\'s skill collection turns your agent into an integration platform. Connect to GitHub for PR and issue automation, Slack for team notifications, Jira for ticket management, and arbitrary REST APIs through a unified natural language interface. The webhook manager rounds it out by letting you set up event-driven workflows without writing glue code.',
    trustTier: 'community',
    audience: 'developer',
    category: 'automation',
    githubUrl: 'https://github.com/composiohq/awesome-skills',
    stars: 2100,
    forks: 160,
    lastUpdated: '2026-03-12',
    license: 'MIT',
    worksWith: ['claude-code', 'cursor'],
    installInstructions: {
      'Claude Code': 'claude install @composiohq/awesome-skills',
      Cursor: 'Add composio-awesome-skills to .cursor/skills/',
    },
    tags: ['integrations', 'github', 'slack', 'jira', 'webhooks'],
    bestFor:
      'Developers who want to automate cross-platform workflows connecting GitHub, Slack, Jira, and APIs.',
    featured: 0,
  },
  {
    slug: 'antigravity',
    name: 'Antigravity',
    author: 'Antigravity',
    authorUrl: 'https://antigravity.dev',
    description:
      'Role-based skill bundles that pre-configure your agent with curated toolkits for frontend, backend, DevOps, data analysis, and product management workflows.',
    summary:
      'Instead of assembling skills one by one, Antigravity gives you complete starter kits organized by role. Pick your bundle — Frontend Developer, Backend Developer, DevOps, Data Analyst, or PM — and get a curated set of skills that work well together. Great for teams onboarding new developers onto Claude Code who want a sensible default configuration.',
    trustTier: 'community',
    audience: 'both',
    category: 'development',
    githubUrl: 'https://github.com/antigravity-official/antigravity',
    stars: 1800,
    forks: 130,
    lastUpdated: '2026-03-10',
    license: 'MIT',
    worksWith: ['claude-code', 'cowork', 'cursor'],
    installInstructions: {
      'Claude Code': 'claude install @antigravity/bundles',
      Cowork: 'Install from Cowork skill marketplace',
    },
    tags: ['bundles', 'onboarding', 'role-based', 'starter-kits', 'curated'],
    bestFor:
      'Teams onboarding new users who want pre-configured, role-based skill bundles instead of manual setup.',
    featured: 0,
  },
  {
    slug: 'compound-engineering',
    name: 'Compound Engineering',
    author: 'Every Inc',
    authorUrl: 'https://every.to',
    description:
      'Full workflow toolkit for AI coding agents with 45 skills and 29 specialized sub-agents. Covers the complete development lifecycle — brainstorm, plan, build, review, compound knowledge, and ship. Includes code style skills (DHH Rails, Andrew Kane gems, DSPy.rb), dev tools (git worktree, browser testing, image generation), content creation (Proof editor, changelogs), and autonomous workflows (LFG, swarm orchestration).',
    summary:
      'The most comprehensive plugin in the ecosystem. Compound Engineering doesn\'t just help you write code — it encodes an entire engineering methodology. From brainstorming requirements through structured planning, implementation with quality gates, multi-agent code review, and knowledge compounding, every phase of shipping software has a dedicated skill. The 29 sub-agents cover security audits, architectural review, performance analysis, design sync, and more.',
    trustTier: 'verified',
    audience: 'both',
    category: 'development',
    githubUrl: 'https://github.com/EveryInc/compound-engineering-plugin',
    stars: 4820,
    forks: 312,
    lastUpdated: '2026-03-18',
    license: 'MIT',
    worksWith: ['claude-code', 'cursor', 'codex'],
    installInstructions: {
      'Claude Code': 'claude install @anthropic/compound-engineering',
      Cursor: 'Install Compound Engineering from Cursor plugins marketplace',
      Codex: 'codex plugin add compound-engineering',
    },
    tags: ['workflow', 'planning', 'code-review', 'knowledge-management', 'brainstorming', 'multi-agent'],
    bestFor:
      'Teams and solo devs who want a complete, opinionated engineering workflow — not just code generation, but the full lifecycle from idea to shipped feature.',
    featured: 1,
  },
  {
    slug: 'notion-workspace',
    name: 'Notion Workspace',
    author: 'Notion Labs',
    authorUrl: 'https://notion.so',
    description:
      'Complete Notion integration with 16 MCP tools and 14 workflow skills. Search your workspace, create and update pages, manage databases and views, track tasks, capture knowledge from conversations, prepare meeting materials, and turn specs into implementation plans — all from your coding agent.',
    summary:
      'The most capable productivity integration available. Notion Workspace goes far beyond basic CRUD — it includes intelligent skills for meeting preparation, knowledge capture from chat conversations, research synthesis across your workspace, and breaking specs into tracked implementation tasks. If your team runs on Notion, this plugin makes your agent a full participant.',
    trustTier: 'official',
    audience: 'both',
    category: 'productivity',
    githubUrl: null,
    stars: null,
    forks: null,
    lastUpdated: '2026-03-15',
    license: null,
    worksWith: ['claude-code', 'cursor', 'cowork'],
    installInstructions: {
      'Claude Code': 'claude mcp add notion -- npx -y @notionhq/notion-mcp-server',
      Cursor: 'Install Notion Workspace from Cursor plugins marketplace',
    },
    tags: ['notion', 'productivity', 'project-management', 'documentation', 'mcp'],
    bestFor:
      'Teams using Notion for project management, documentation, and knowledge bases who want their agent to read, write, and reason about their workspace.',
    featured: 1,
  },
  {
    slug: 'browser-tools',
    name: 'Browser Tools',
    author: 'Cursor',
    authorUrl: 'https://cursor.com',
    description:
      'Full browser automation MCP with 33 tools for navigating pages, interacting with elements, filling forms, taking screenshots, profiling performance, and inspecting network requests. Provides your coding agent with a real browser for testing and validating UI changes.',
    summary:
      'Gives your agent a real browser. Navigate pages, click elements, fill forms, take screenshots, profile CPU performance, and inspect network requests — all driven by natural language. Essential for frontend development workflows where you need to verify UI changes visually.',
    trustTier: 'verified',
    audience: 'developer',
    category: 'automation',
    githubUrl: null,
    stars: null,
    forks: null,
    lastUpdated: '2026-03-12',
    license: null,
    worksWith: ['cursor'],
    installInstructions: {
      Cursor: 'Built-in with Cursor IDE browser integration',
    },
    tags: ['browser', 'testing', 'automation', 'screenshots', 'profiling', 'mcp'],
    bestFor:
      'Frontend developers who want their agent to visually verify UI changes, run browser-based tests, and profile web application performance.',
    featured: 0,
  },
];
